name: Bybit ADA/USDT Auto Trading Polling

on:
  schedule:
    - cron: '*/3 * * * *'    # 每 3 分钟触发一次（UTC 时间）
  workflow_dispatch:

jobs:
  trade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 确保安装了 CryptoCompare 版 auto_trade.py 需要的所有包
          pip install pandas numpy requests pybit

      - name: Run auto_trade.py
        run: python auto_trade.py
        env:
          BYBIT_API_KEY:    ${{ secrets.BYBIT_API_KEY }}
          BYBIT_API_SECRET: ${{ secrets.BYBIT_API_SECRET }}
