# .github/workflows/auto-trade.yml
name: Bybit ADA/USDT Auto Trading Polling

on:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:

jobs:
  trade:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 你的程式碼
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 設定 Python 3.9
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. 安裝相容的 numpy 與 pandas-ta，然後安裝其餘套件
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 先安裝一個和 pandas-ta v0.3.14b0 兼容的 numpy
          pip install numpy==1.21.0
          # 再刻意指定 pandas-ta 版本為 0.3.14b0
          pip install pandas-ta==0.3.14b0
          # 最後安裝 pandas 與 pybit
          pip install pandas pybit

      # 4. 執行 auto_trade.py，並且將 Secrets 注入到環境變數
      - name: Run auto_trade.py
        run: python auto_trade.py
        env:
          BYBIT_API_KEY:    ${{ secrets.BYBIT_API_KEY }}
          BYBIT_API_SECRET: ${{ secrets.BYBIT_API_SECRET }}
