# .github/workflows/auto-trade.yml
name: Bybit ADA/USDT Auto Trading Polling

on:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:

jobs:
  trade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # 1) 先安装一个兼容 pandas-ta 的 numpy 旧版
          pip install numpy==1.21.0
          # 2) 再安装 pandas、pandas-ta、pybit
          pip install pandas pandas-ta pybit

      - name: Run auto_trade.py
        run: python auto_trade.py
        env:
          BYBIT_API_KEY:    ${{ secrets.BYBIT_API_KEY }}
          BYBIT_API_SECRET: ${{ secrets.BYBIT_API_SECRET }}
