# 文件路径：.github/workflows/auto_trade.yml
name: "Auto Trade Bot"

on:
  # 每小时跑一次，也可以改成每 4 小时一次：'0 */4 * * *'
  schedule:
    - cron: '0 * * * *'  # 每整点执行一次

  # 也可以手动触发
  workflow_dispatch:

jobs:
  run_auto_trade:
    name: Run Auto Trade Script
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 代码
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # 允许本 workflow 将修改后的状态文件 push 回仓库
          persist-credentials: true
          fetch-depth: 0

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-binance pandas numpy

      # 4. 运行脚本
      - name: Run auto_trade.py
        env:
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
        run: |
          cd auto_trade
          python auto_trade.py

      # 5. 检查 state.json 是否有改动，如果有，就提交并推送
      - name: Commit state changes
        run: |
          cd auto_trade
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain state.json)" ]]; then
            git add state.json
            git commit -m "Update state.json [skip ci]"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No state changes to commit."
          fi
